### ISSUE TITLE
com.github.tobato.fastdfs.exception.FdfsConnectException: 无法获取服务端连接资源 端口号为0

### ISSUE THREAD

**Issue by fxkjnj** [happyfish100/fastdfs-client-java#113]
com.github.tobato.fastdfs.exception.FdfsConnectException: 无法获取服务端连接资源 端口号为0
版本： 6.12.1

**Comment by happyfish100** [comment]
为了支持 IPv6，返回的IP 地址长度由 16 改为 46。
友情提示：tobato这个第三方 SDK 有已知 bug，强烈建议使用官方提供的 SDK。

**Comment by zhanghang1833** [comment]
org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:175) - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.github.tobato.fastdfs.exception.FdfsConnectException: 无法获取服务端连接资源：can't create connection toip Y:23000] with root cause
java.net.UnknownHostException: ip Y
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:196) ~[?:1.8.0_411]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394) ~[?:1.8.0_411]
	at java.net.Socket.connect(Socket.java:606) ~[?:1.8.0_411]
	at com.github.tobato.fastdfs.domain.conn.DefaultConnection.<init>(DefaultConnection.java:54) ~[fastdfs-client-1.27.2.jar:1.27.2]
	at com.github.tobato.fastdfs.domain.conn.PooledConnectionFactory.create(PooledConnectionFactory.java:56) ~[fastdfs-client-1.27.2.jar:1.27.2]
	at com.github.tobato.fastdfs.domain.conn.PooledConnectionFactory.create(PooledConnectionFactory.java:22) ~[fastdfs-client-1.27.2.jar:1.27.2]
	at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:82) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:780) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:439) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:350) ~[commons-pool2-2.11.1.jar:2.11.1]
	at com.github.tobato.fastdfs.domain.conn.FdfsConnectionManager.getConnection(FdfsConnectionManager.java:148) ~[fastdfs-client-1.27.2.jar:1.27.2]
	at com.github.tobato.fastdfs.domain.conn.FdfsConnectionManager.executeFdfsCmd(FdfsConnectionManager.java:63) ~[fastdfs-client-1.27.2.jar:1.27.2]
	at com.github.tobato.fastdfs.service.DefaultGenerateStorageClient.queryFileInfo(DefaultGenerateStorageClient.java:102) ~[fastdfs-client-1.27.2.jar:1.27.2]
	at com.crscd.product.manager.sys.service.FastFdsUpDownService.downloadFile(FastFdsUpDownService.java:417) ~[P3fkv5aqYU/:?]

**Comment by zhanghang1833** [comment]
无法获取服务端连接资源 ip Y:23000
为什么ip后面会拼一个Y

**Comment by rea-leaf** [comment]
客户端是否可以兼容老版本的fastdfs server ，做好可以自动判断ip的长度是16 还是46

> 为了支持 IPv6，返回的IP 地址长度由 16 改为 46。
