### ISSUE TITLE
recv cmd: 32 is not correct, expect cmd: 100

### ISSUE THREAD

**Issue by github20151005** [happyfish100/fastdfs-client-java#24]
服务器端可以正常上传 使用java client 1.27 就不行了，这是什么原因啊？（客户端的配置文件加载成功了）

 `java.io.IOException: recv cmd: 32 is not correct, expect cmd: 100
	at org.csource.fastdfs.ProtoCommon.recvHeader(ProtoCommon.java:173)
	at org.csource.fastdfs.ProtoCommon.recvPackage(ProtoCommon.java:201)
	at org.csource.fastdfs.TrackerClient.getStoreStorage(TrackerClient.java:130)
	at org.csource.fastdfs.StorageClient.newWritableStorageConnection(StorageClient.java:1627)
	at org.csource.fastdfs.StorageClient.do_upload_file(StorageClient.java:639)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:162)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:180)
	at FastDFS.uploadFile(FastDFS.java:105)
	at FastDFS.main(FastDFS.java:265)
java.lang.NullPointerException
	at FastDFS.main(FastDFS.java:266)`

**Comment by github20151005** [comment]
问题解决了，主要是tracker_server的端口写错了。服务器是别搭建的，端口给错了。不是客户端的原因。

**Comment by wya-jun** [comment]
遇到同样的问题，是什么端口错了？能不能贴一下 配置文件

**Comment by RobinsChens** [comment]
我的是第一次上传失败，第二次就成功了，无语

**Comment by xiwen369** [comment]
一直报这个错，加锁什么的都试过了，但是都不行啊

**Comment by chuaiwei** [comment]
> 一直报这个错，加锁什么的都试过了，但是都不行啊

解决了吗？我也缠住了...
