### ISSUE TITLE
recv package size -1 != 10

### ISSUE THREAD

**Issue by itlidaye** [happyfish100/fastdfs-client-java#38]
java.io.IOException: recv package size -1 != 10
	at org.csource.fastdfs.ProtoCommon.recvHeader(ProtoCommon.java:169)
	at org.csource.fastdfs.ProtoCommon.recvPackage(ProtoCommon.java:201)
	at org.csource.fastdfs.TrackerClient.getStoreStorage(TrackerClient.java:130)
	at org.csource.fastdfs.StorageClient.newWritableStorageConnection(StorageClient.java:1627)

这个怎么回事
![qq 20180524123153](https://user-images.githubusercontent.com/15826407/40464581-90863436-5f4e-11e8-898d-3b0969318022.jpg)

**Comment by happyfish100** [comment]
应该是连接断掉了。
另外可以看下tracker server日志。

**Comment by itlidaye** [comment]
启动服务后  第一次 上传 会这样  后面就不会了

**Comment by Ganvor1124** [comment]
我也遇到：
1. 第一次上传会出现这个错误，增加重试后解决；
2. 后面还有遇到，是由于我构造StorageClient时传入了自己的StorageServer，查看StorageClient代码是内部在storage为空时，会自动构建且区分Updatable, Readable, Writable不同的Storage。于是，我构造StorageClient时不传入StorageServer，仅传入TrackerServer后解决。
