### ISSUE TITLE
每次new也会报

### ISSUE THREAD

**Issue by git0717** [happyfish100/fastdfs-client-java#40]
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at org.csource.fastdfs.ProtoCommon.recvHeader(ProtoCommon.java:168)
	at org.csource.fastdfs.ProtoCommon.recvPackage(ProtoCommon.java:201)
	at org.csource.fastdfs.TrackerClient.getStoreStorage(TrackerClient.java:130)
	at org.csource.fastdfs.StorageClient.newWritableStorageConnection(StorageClient.java:1627)
	at org.csource.fastdfs.StorageClient.do_upload_file(StorageClient.java:639)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:162)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:180)
	at org.csource.fastdfs.StorageClient1.upload_file1(StorageClient1.java:103)

**Comment by happyfish100** [comment]
看tracker server日志报什么错
