### ISSUE TITLE
linux  运行原时间 Caused by: java.net.SocketException: Broken pipe (Write failed)

### ISSUE THREAD

**Issue by kbp1234** [happyfish100/fastdfs-client-java#44]
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_172]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[na:1.8.0_172]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143) ~[na:1.8.0_172]

**Comment by happyfish100** [comment]
用了长连接或连接池吧，是网络连接断掉了。这个偶发出现不是什么问题，可以忽略。

**Comment by kbp1234** [comment]
代码中用了连接池，不是偶发（已经在服务器上测试过两次了），每隔10天左右，线上出现这个问题后文件就不能上传了，想咨询下您 这种问题有什么好的解决方案没？是不是不能使用连接池啊

**Comment by happyfish100** [comment]
当然可以使用连接池。对于失效的连接，需要重连。

**Comment by kbp1234** [comment]
嗯，谢谢

**Comment by zhengpingzhong** [comment]
请问这个问题最后如何解决的呢？

**Comment by yuboliang** [comment]
你好，请问后面你们如何解决这个问题，我这边也发生了这种问题。如何重连失效的连接呢？

**Comment by zhengpingzhong** [comment]
这个看用的哪个第三方。之前有个java客户端是直接把连接池去掉就好了。



郑平中 18811331575
pingzhong.zheng@foxmail.com
 
发件人： yuboliang
发送时间： 2019-11-27 14:10
收件人： happyfish100/fastdfs-client-java
抄送： Alex; Comment
主题： Re: [happyfish100/fastdfs-client-java] fastdfs集群 运行10天时间，就会出现这个问题 Caused by: java.net.SocketException: Broken pipe (Write failed) (#44)
你好，请问后面你们如何解决这个问题，我这边也发生了这种问题。如何重连失效的连接呢？

**Comment by liukuankuan** [comment]
你好，请问如何解决这个问题呢？我这边也出现了这个问题

**Comment by kzdwts** [comment]
我也出现了，怎么处理呀？

**Comment by crazyStar00** [comment]
使用连接池，并且失败应该自动重试。
