### ISSUE TITLE
在使用TrackerClient中的listStorage方法出错

### ISSUE THREAD

**Issue by zeq9069** [happyfish100/fastdfs-client-java#6]
fastdfs-client-java v1.25在跟fastdfs-v5.03进行交互时，TrackerClient中的listStorage方法出错~~    

最后发现是通信协议这一块出问题了，StructStorageStat中的变量跟服务端返回的二进制消息中的参数不一致~~~
StructStorageStat 中的以下四个参数，在fastdfs-v5.03返回的二进制消息中是没有的！！

protected long connectionAllocCount;
protected long connectionCurrentCount;
protected long connectionMaxCount;
protected boolean ifTrunkServer;

删掉这四个变量就可以额~~

错误如下：

java.io.IOException: byte array length: 1200 is invalid!
	at org.csource.fastdfs.ProtoStructDecoder.decode(ProtoStructDecoder.java:38)
	at org.csource.fastdfs.TrackerClient.listStorages(TrackerClient.java:752)
	at org.csource.fastdfs.TrackerClient.listStorages(TrackerClient.java:661)

**Comment by happyfish100** [comment]
server端版本太低，升级到最新版本就没问题了。

**Comment by zeq9069** [comment]
OK
