### ISSUE TITLE
storageClient调用get_file_info方法出现java.lang.ArrayIndexOutOfBoundsException错误

### ISSUE THREAD

**Issue by davidSeven** [happyfish100/fastdfs-client-java#64]
这个是调用的信息，上传，下载，删除方法都可以调用。
get_file_info就是这个方法调用出错
FileInfo fi = storageClient.get_file_info("group1", "M00/00/00/wKgKs11x4TWASa5AAACi1jeGYIs657.jpg");

错误日志：
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Input to decode not an even multiple of 4 characters; pad with =.
	at org.csource.common.Base64.decode(Base64.java:319)
	at org.csource.common.Base64.decodeAuto(Base64.java:241)
	at org.csource.fastdfs.StorageClient.get_file_info(StorageClient.java:1113)

**Comment by LiYeLin** [comment]
俺也一样 ，但是看来作者已经放弃解答issue
