### ISSUE TITLE
fastdfs集群部署了两个tracker，手动停止一个tracker，使用客户端上传文件10个，5个成功，5个失败

### ISSUE THREAD

**Issue by Qi-Zou** [happyfish100/fastdfs-client-java#76]
org.csource.common.MyException: connect to server 172.xxx.xxx.xxx:22122 fail, emsg:Connection refused: connect
	at org.csource.fastdfs.pool.ConnectionFactory.create(ConnectionFactory.java:26) ~[fastdfs-client-java-1.29.jar:?]
	at org.csource.fastdfs.pool.ConnectionManager.getConnection(ConnectionManager.java:76) ~[fastdfs-client-java-1.29.jar:?]
	at org.csource.fastdfs.pool.ConnectionPool.getConnection(ConnectionPool.java:32) ~[fastdfs-client-java-1.29.jar:?]
	at org.csource.fastdfs.TrackerServer.getConnection(TrackerServer.java:36) ~[fastdfs-client-java-1.29.jar:?]
	at org.csource.fastdfs.TrackerClient.listGroups(TrackerClient.java:485) ~[fastdfs-client-java-1.29.jar:?]

**Comment by rui8832** [comment]
建议使用服务端负载均衡和高可用方案呢

**Comment by zwyacg** [comment]
我这儿遇到了同样的问题，只能依靠服务器端的负载均衡来处理吗？
